{
 "title": "Flink",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job_name) (flink_jobmanager_job_uptime)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Fan out ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (job_name) (flink_taskmanager_job_task_operator_KafkaConsumer_incoming_byte_rate) / avg by (job_name) (flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Number of records out per second (grouped by subtasks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name,subtask_index) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond)",
     "legendFormat": "{{job_name}} {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Number of records out per second (grouped by jobs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name) (flink_taskmanager_job_task_operator_numRecordsOutPerSecond)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job_name) (flink_taskmanager_job_task_operator_KafkaConsumer_records_lag_max)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (job_name) (flink_taskmanager_job_task_operator_KafkaConsumer_commit_latency_avg)",
     "legendFormat": "{{job_name}} Commit Latency"
    },
    {
     "expr": "avg by (job_name) (flink_taskmanager_job_task_operator_KafkaConsumer_fetch_latency_avg)",
     "legendFormat": "{{job_name}} Fetch Latency"
    },
    {
     "expr": "avg by (job_name) (flink_taskmanager_job_task_operator_KafkaProducer_request_latency_avg)",
     "legendFormat": "{{job_name}} Request Latency"
    },
    {
     "expr": "avg by (job_name) (flink_jobmanager_job_restartingTime)",
     "legendFormat": "{{job_name}} Restarting Time"
    }
   ]
  },
  {
   "title": "KafkaConsumer incoming byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name) (flink_taskmanager_job_task_operator_KafkaConsumer_incoming_byte_rate)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "KafkaProducer outgoing byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (job_name) (flink_taskmanager_job_task_operator_KafkaProducer_outgoing_byte_rate))",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "KafkaConsumer bytes consumed rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name, subtask_index) (flink_taskmanager_job_task_operator_KafkaConsumer_bytes_consumed_rate)",
     "legendFormat": "{{job_name}} {{subtask_index}}"
    }
   ]
  },
  {
   "title": "Operator incoming byte rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name, subtask_index) (flink_taskmanager_job_task_operator_incoming_byte_rate)",
     "legendFormat": "{{job_name}} {{subtask_index}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_CPU_Load)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_Threads_Count)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_Memory_Heap_Committed)",
     "legendFormat": "{{host}} Committed"
    },
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_Memory_Heap_Used)",
     "legendFormat": "{{host}} Used"
    }
   ]
  },
  {
   "title": "Non-heap memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_Memory_NonHeap_Committed)",
     "legendFormat": "{{host}} Committed"
    },
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_Memory_NonHeap_Used)",
     "legendFormat": "{{host}} Used"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (idelta (flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Time[1h]))",
     "legendFormat": "{{host}} scavange"
    },
    {
     "expr": "avg by (host) (idelta (flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Time[1h]))",
     "legendFormat": "{{host}} marksweep"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_GarbageCollector_PS_MarkSweep_Count)",
     "legendFormat": "{{host}} MarkSweep"
    },
    {
     "expr": "avg by (host) (flink_jobmanager_Status_JVM_GarbageCollector_PS_Scavenge_Count)",
     "legendFormat": "{{host}} Scavange"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_consumergroup_lag)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka current offset sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_consumergroup_current_offset_sum)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka number of partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (kafka_topic_partitions)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}